# Generated by Django 4.1.4 on 2022-12-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useracount',
            managers=[
            ],
        ),
    ]
